services:

  oracle-db:
    build: ./oracle-db
    container_name: oracle-simple
    environment:
      ORACLE_PASSWORD: Oracle123
      APP_USER: AGENDA
      APP_USER_PASSWORD: AG3nd5
    ports:
      - "1521:1521"
    networks:
      - app-network
    volumes:
      - oracle-data-app-v1:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    mem_limit: 3g
    shm_size: 2g

networks:
  app-network:
    driver: bridge

volumes:
  oracle-data-app-v1: